DROP TABLE IF EXISTS CORE__CATEGORIES;
CREATE TABLE IF NOT EXISTS Cricket.CORE__CATEGORIES (
    id INT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    sport_id INT,
    FOREIGN KEY (sport_id) REFERENCES config.sports(id)
);