USE Cricket;
DROP TABLE IF EXISTS CORE__LEAGUESEASONS;
CREATE TABLE CORE__LEAGUESEASONS (
    id INT PRIMARY KEY,
    editor BOOLEAN,
    name VARCHAR(255) NOT NULL,
    year VARCHAR(5) NOT NULL,
    tournament_id INT NOT NULL,
FOREIGN KEY (tournament_id) REFERENCES CORE__TOURNAMENTS(id)
)