DROP TABLE IF EXISTS config.jobs;
CREATE TABLE config.jobs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    layer_comp_name VARCHAR(255),
    markers VARCHAR(255),
    layer_comp_type VARCHAR(50),
    media_type VARCHAR(50), -- file/text/none
    is_trim BOOLEAN,
    is_sync BOOLEAN,
    is_marker BOOLEAN,
    parent_comp VARCHAR(255)
  );

INSERT INTO config.jobs (layer_comp_name, markers, layer_comp_type, media_type, is_trim, is_sync, is_marker, parent_comp) VALUES 
('0_Main comp', '', 'comp', 'none', true, false, false, 'project'),
('Empty Transition', '', 'comp', 'none', false, false, false, '0_Main comp'),
('0_Final comp', '', 'comp', 'none', false, true, false, '0_Main comp'),
('trans-presOpen-news1', '', 'comp', 'none', false, true, false, '0_Main comp'),
('Presentor Open', '', 'comp', 'none', true, true, false, '0_Main comp'),
('trans-news1-news2', '', 'comp', 'none', false, true, false, '0_Main comp'),
('News comp 1', '', 'comp', 'none', true, true, false, '0_Main comp'),
('trans-news2-presClose', '', 'comp', 'none', false, true, false, '0_Main comp'),
('News comp 2', '', 'comp', 'none', true, true, false, '0_Main comp'),
('presentor close ', '', 'comp', 'none', true, true, false, '0_Main comp'),
('Intro', 'out', 'comp', 'none', false, true, false, '0_Main comp'),
('INTRO SOUND', 'Loop in', 'comp', 'none', true, true, true, '0_Main comp'),
('Intro news III Loop', 'Loop in', 'comp', 'none', true, true, true, '0_Main comp'),
('Ending', 'out', 'comp', 'none', true, true, true, '0_Main comp'),
('News-BG1', '', 'comp', 'file', true, true, false, 'News comp 1'),
('News-BG2', '', 'comp', 'file', true, true, false, 'News comp 1'),
('News-BG3', '', 'comp', 'file', true, true, false, 'News comp 1'),
('News-Narration1', '', 'comp', 'file', true, true, false, 'News comp 1'),
('News-Narration2', '', 'comp', 'file', true, true, false, 'News comp 1'),
('News-Narration3', '', 'comp', 'file', true, true, false, 'News comp 1'),
('Todyas news 1', 'News1,News2,News3', 'comp', 'none', true, false, true, 'News comp 1'),
('date_tab_01', '', 'comp', 'none', false, false, false, 'News comp 1'),
('Bottom Ticker', '', 'comp', 'none', false, false, false, 'News comp 1'),
('News BG', '', 'comp', 'none', false, false, false, 'News comp 1'),
('Disclaimer', '', 'comp', 'none', false, false, false, 'News comp 1'),
('Text color', '', 'layer', 'none', false, false, false, 'Todyas news 1'),
('Font size', '', 'layer', 'none', false, false, false, 'Todyas news 1'),
('all layers control', '', 'layer', 'none', false, false, false, 'Todyas news 1'),
('action', 'News1,News2,News3', 'layer', 'none', false, false, true, 'Todyas news 1'),
('Scuhedule ticker 1', '', 'comp', 'none', true, true, false, 'Todyas news 1'),
('Scuhedule ticker 2', '', 'comp', 'none', true, true, false, 'Todyas news 1'),
('Scuhedule ticker 3', '', 'comp', 'none', true, true, false, 'Todyas news 1'),
('Ranking-News1', '', 'comp', 'none', true, true, false, 'Todyas news 1'),
('Ranking-News2', '', 'comp', 'none', true, true, false, 'Todyas news 1'),
('Ranking-News3', '', 'comp', 'none', true, true, false, 'Todyas news 1'),
('News-logo1', '', 'comp', 'file', true, true, false, 'Todyas news 1'),
('News-logo2', '', 'comp', 'file', true, true, false, 'Todyas news 1'),
('News-logo3', '', 'comp', 'file', true, true, false, 'Todyas news 1'),
('Headline1', '', 'layer', 'text', true, true, false, 'Todyas news 1'),
('Headline2', '', 'layer', 'text', true, true, false, 'Todyas news 1'),
('Headline3', '', 'layer', 'text', true, true, false, 'Todyas news 1'),
('Black Solid 276', '', 'layer', 'none', false, false, false, 'Todyas news 1'),
('headlinetext11', '', 'layer', 'text', true, true, false, 'Todyas news 1'),
('headlinetext12', '', 'layer', 'text', true, true, false, 'Todyas news 1'),
('headlinetext13', '', 'layer', 'text', true, true, false, 'Todyas news 1'),
('News BG', '', 'comp', 'none', false, false, false, 'Todyas news 1'),
('MattCurrenciesCurrencies CloseStocks', '', '', 'none', false, false, false, 'Scuhedule ticker 1'),
('Ticker data 1', '', '', 'none', false, false, false, 'Scuhedule ticker 1'),
('Black Solid 4CurrenciesCurrencies CloseStocks', '', '', 'none', false, false, false, 'Scuhedule ticker 1'),
('Match1-1', '', 'comp', 'none', false, false, false, 'Ticker data 1'),
('Match1-2', '', 'comp', 'none', false, false, false, 'Ticker data 1'),
('Match1-3', '', 'comp', 'none', false, false, false, 'Ticker data 1'),
('Match1-4', '', 'comp', 'none', false, false, false, 'Ticker data 1'),
('Match1-5', '', 'comp', 'none', false, false, false, 'Ticker data 1'),
('Match1-6', '', 'comp', 'none', false, false, false, 'Ticker data 1'),
('Match1-7', '', 'comp', 'none', false, false, false, 'Ticker data 1'),
('Match1-8', '', 'comp', 'none', false, false, false, 'Ticker data 1'),
('Match1-9', '', 'comp', 'none', false, false, false, 'Ticker data 1'),
('Match1-10', '', 'comp', 'none', false, false, false, 'Ticker data 1'),
('Schedule-away-team-1-1', '', 'layer', 'text', false, false, false, 'Match1-1'),
('Schedule-home-team-1-1', '', 'layer', 'text', false, false, false, 'Match1-1'),
('game-time-1-1', '', 'layer', 'text', false, false, false, 'Match1-1'),
('game-date-1-1', '', 'layer', 'text', false, false, false, 'Match1-1'),
('schedule-home-team-logo-1-1', '', 'comp', 'file', false, false, false, 'Match1-1'),
('schedule-away-team-logo-1-1', '', 'comp', 'file', false, false, false, 'Match1-1'),
('Schedule BG', '', 'comp', 'none', false, false, false, 'Match1-1'),
('RankingList news 1', '', 'comp', 'none', false, false, false, 'Ranking-News1'),
('side_panel_main', '', 'comp', 'none', false, false, false, 'Ranking-News1'),
('Ranking-header-1', '', 'comp', 'text', false, false, false, 'Ranking-News1'),
('1_side_panel_title/logo', '', 'comp', 'none', false, false, false, 'Ranking-News1'),
('layernumbers', '', 'layer', 'none', false, false, false, 'RankingList news 1'),
('Adjustment Layer 19', '', 'layer', 'none', false, false, false, 'RankingList news 1'),
('Stats-ranking_header 1', '', 'comp', 'none', false, false, false, 'RankingList news 1'),
('RN11', '', 'comp', 'none', false, false, false, 'RankingList news 1'),
('RN12', '', 'comp', 'none', false, false, false, 'RankingList news 1'),
('RN13', '', 'comp', 'none', false, false, false, 'RankingList news 1'),
('RN14', '', 'comp', 'none', false, false, false, 'RankingList news 1'),
('RN15', '', 'comp', 'none', false, false, false, 'RankingList news 1'),
('RN16', '', 'comp', 'none', false, false, false, 'RankingList news 1'),
('RN17', '', 'comp', 'none', false, false, false, 'RankingList news 1'),
('RN18', '', 'comp', 'none', false, false, false, 'RankingList news 1'),
('RN19', '', 'comp', 'none', false, false, false, 'RankingList news 1'),
('RN110', '', 'comp', 'none', false, false, false, 'RankingList news 1'),
('Stats-ranking1.1', '', 'comp', 'none', false, false, false, 'RN11'),
('ranking-name-team1-1', '', 'layer', 'text', false, false, false, 'RN11'),
('tab_build_medium_B', '', 'comp', 'none', false, false, false, 'RN11'),
('ranking-stat1-header1', '', 'layer', 'text', false, false, false, 'Stats-ranking_header 1'),
('ranking-stat2-header1', '', 'layer', 'text', false, false, false, 'Stats-ranking_header 1'),
('ranking-stat4-header1', '', 'layer', 'text', false, false, false, 'Stats-ranking_header 1'),
('ranking-stat3-header1', '', 'layer', 'text', false, false, false, 'Stats-ranking_header 1'),
('ranking-stat5-header1', '', 'layer', 'text', false, false, false, 'Stats-ranking_header 1'),
('ranking-stat1-team1-1', '', 'layer', 'text', false, false, false, 'Stats-ranking1.1'),
('ranking-stat2-team1-1', '', 'layer', 'text', false, false, false, 'Stats-ranking1.1'),
('ranking-stat3-team1-1', '', 'layer', 'text', false, false, false, 'Stats-ranking1.1'),
('ranking-stat4-team1-1', '', 'layer', 'text', false, false, false, 'Stats-ranking1.1'),
('ranking-stat5-team1-1', '', 'layer', 'text', false, false, false, 'Stats-ranking1.1'),
('Adjustment Layer 19', '', 'layer', 'none', false, false, false, 'Stats-ranking1.1'),
('RankingList news 2', '', 'comp', 'none', false, false, false, 'Ranking-News2'),
('side_panel_main', '', 'comp', 'none', false, false, false, 'Ranking-News2'),
('Ranking-header-2', '', 'comp', 'text', false, false, false, 'Ranking-News2'),
('1_side_panel_title/logo', '', 'comp', 'none', false, false, false, 'Ranking-News2'),
('layernumbers', '', 'layer', 'none', false, false, false, 'RankingList news 2'),
('Adjustment Layer 19', '', 'layer', 'none', false, false, false, 'RankingList news 2'),
('Stats-ranking_header 1', '', 'comp', 'none', false, false, false, 'RankingList news 2'),
('RN21', '', 'comp', 'none', false, false, false, 'RankingList news 2'),
('RN22', '', 'comp', 'none', false, false, false, 'RankingList news 2'),
('RN23', '', 'comp', 'none', false, false, false, 'RankingList news 2'),
('RN24', '', 'comp', 'none', false, false, false, 'RankingList news 2'),
('RN25', '', 'comp', 'none', false, false, false, 'RankingList news 2'),
('RN26', '', 'comp', 'none', false, false, false, 'RankingList news 2'),
('RN27', '', 'comp', 'none', false, false, false, 'RankingList news 2'),
('RN28', '', 'comp', 'none', false, false, false, 'RankingList news 2'),
('RN29', '', 'comp', 'none', false, false, false, 'RankingList news 2'),
('RN210', '', 'comp', 'none', false, false, false, 'RankingList news 2'),
('Stats-ranking2.3', '', 'comp', 'none', false, false, false, 'RN23'),
('ranking-name-team2-3', '', 'layer', 'text', false, false, false, 'RN23'),
('tab_build_medium_B', '', 'comp', 'none', false, false, false, 'RN23'),
('ranking-stat1-team2-3', '', 'layer', 'text', false, false, false, 'Stats-ranking2.3'),
('ranking-stat2-team2-3', '', 'layer', 'text', false, false, false, 'Stats-ranking2.3'),
('ranking-stat3-team2-3', '', 'layer', 'text', false, false, false, 'Stats-ranking2.3'),
('ranking-stat4-team2-3', '', 'layer', 'text', false, false, false, 'Stats-ranking2.3'),
('ranking-stat5-team2-3', '', 'layer', 'text', false, false, false, 'Stats-ranking2.3'),
('Adjustment Layer 19', '', 'layer', 'none', false, false, false, 'Stats-ranking2.3'),
('Todyas news 2', 'News4, News5', 'comp', 'none', true, false, true, 'News comp 2'),
('date_tab_01', '', 'comp', 'none', false, false, false, 'News comp 2'),
('Bottom Ticker', '', 'comp', 'none', false, false, false, 'News comp 2'),
('News BG', '', 'comp', 'none', false, false, false, 'News comp 2'),
('Scuhedule ticker 1', '', 'comp', 'none', false, false, false, 'News comp 2'),
('Disclaimer', '', 'comp', 'none', false, false, false, 'News comp 2'),
('News-BG5', '', 'comp', 'file', true, true, false, 'News comp 2'),
('News-BG4', '', 'comp', 'file', true, true, false, 'News comp 2'),
('News-Narration4', '', 'comp', 'file', true, true, false, 'News comp 2'),
('News-Narration5', '', 'comp', 'file', true, true, false, 'News comp 2'),
('Font size', '', 'layer', 'none', false, false, false, 'Todyas news 2'),
('all layers control', '', 'layer', 'none', false, false, false, 'Todyas news 2'),
('action', 'News4, News5', 'layer', 'none', false, false, false, 'Todyas news 2'),
('Ranking-News5', '', 'comp', 'none', true, true, false, 'Todyas news 2'),
('Scuhedule ticker 5', '', 'comp', 'none', true, true, false, 'Todyas news 2'),
('Scuhedule ticker 4', '`', 'comp', 'none', true, true, false, 'Todyas news 2'),
('Ranking-News4', '', 'comp', 'none', true, true, false, 'Todyas news 2'),
('Black Solid 276', '', 'layer', 'none', false, false, false, 'Todyas news 2'),
('News-logo5', '', 'comp', 'file', true, true, false, 'Todyas news 2'),
('News-logo4', '', 'comp', 'file', true, true, false, 'Todyas news 2'),
('Headline4', '', 'layer', 'text', true, true, false, 'Todyas news 2'),
('Headline5', '', 'layer', 'text', true, true, false, 'Todyas news 2'),
('Black Solid 276', '', 'layer', 'none', false, false, false, 'Todyas news 2'),
('headlinetext41', '', 'layer', 'text', true, true, false, 'Todyas news 2'),
('headlinetext51', '', 'layer', 'text', true, true, false, 'Todyas news 2'),
('News BG', '', 'comp', 'none', false, false, false, 'Todyas news 2');