
DROP TABLE IF EXISTS AmericanFootball.RAPID__PLAYER_STATISTICS;
CREATE TABLE IF NOT EXISTS AmericanFootball.RAPID__PLAYER_STATISTICS (
    id VARCHAR(20) NOT NULL,
    league_season_id INT NOT NULL,
    player_id VARCHAR(255) NOT NULL,
    PRIMARY KEY (league_season_id, player_id),
    FOREIGN KEY (player_id) REFERENCES AmericanFootball.CORE__PLAYERS(id),
    FOREIGN KEY (league_season_id) REFERENCES AmericanFootball.CORE__LEAGUESEASONS(id),

    appearances VARCHAR(20),
    type VARCHAR(20),

        defensiveAssistTackles VARCHAR(20),
        defensiveCombineTackles VARCHAR(20),
        defensiveForcedFumbles VARCHAR(20),
        defensiveInterceptions VARCHAR(20),
        defensivePassesDefensed VARCHAR(20),
        defensiveSacks VARCHAR(20),
        defensiveSafeties VARCHAR(20),
        defensiveTotalTackles VARCHAR(20),
        fumbleFumbles VARCHAR(20),
        fumbleLost VARCHAR(20),
        fumbleOpponentFumbleRecovery VARCHAR(20),
        fumbleTeammateFumbleRecovery VARCHAR(20),
        fumbleFumblesOutbounds VARCHAR(20),
        fumbleTeammateFumbleYards VARCHAR(20),
        fumbleTeammateFumbleTd VARCHAR(20),
        fumbleOpponentFumbleYards VARCHAR(20),
        fumbleOpponentFumbleTd VARCHAR(20),
        kickReturnsAverageYards VARCHAR(20),
        kickReturnsLong VARCHAR(20),
        kickReturnsTotal VARCHAR(20),
        kickReturnsTouchdowns VARCHAR(20),
        kickReturnsYards VARCHAR(20),
        kickReturnsFairCatches VARCHAR(20),
        kickReturnsLgtd VARCHAR(20),
        kickingExtraAttempts VARCHAR(20),
        kickingExtraMade VARCHAR(20),
        kickingExtraPercentage VARCHAR(20),
        kickingFgAttempts VARCHAR(20),
        kickingFgAttempts20to29 VARCHAR(20),
        kickingFgAttempts30to39 VARCHAR(20),
        kickingFgAttempts40to49 VARCHAR(20),
        kickingFgAttempts50plus VARCHAR(20),
        kickingFgBlocked VARCHAR(20),
        kickingFgLong VARCHAR(20),
        kickingFgMade VARCHAR(20),
        kickingFgMade20to29 VARCHAR(20),
        kickingFgMade30to39 VARCHAR(20),
        kickingFgMade40to49 VARCHAR(20),
        kickingFgMade50plus VARCHAR(20),
        kickingFgPercentage VARCHAR(20),
        kickingFgAttempts1to19 VARCHAR(20),
        kickingFgMade1to19 VARCHAR(20),
        kickingExtraBlocked VARCHAR(20),
        kickoffReturnYards VARCHAR(20),
        kickoffTotal VARCHAR(20),
        kickoffTouchbacks VARCHAR(20),
        kickoffYards VARCHAR(20),
        kickoffOutbounds VARCHAR(20),
        kickoffOnside VARCHAR(20),
        passingAttempts VARCHAR(20),
        passingCompletionPercentage VARCHAR(20),
        passingCompletions VARCHAR(20),
        passingInterceptions VARCHAR(20),
        passingLongest VARCHAR(20),
        passingNetYards VARCHAR(20),
        passingSacked VARCHAR(20),
        passingTouchdowns VARCHAR(20),
        passingYards VARCHAR(20),
        passingYardsPerAttempt VARCHAR(20),
        passingLongTouchdown VARCHAR(20),
        passingSackedYardsLost VARCHAR(20),
        passingFirstDowns VARCHAR(20),
        passingPasserRating VARCHAR(20),
        puntReturnsLong VARCHAR(20),
        puntReturnsTotal VARCHAR(20),
        puntReturnsTouchdowns VARCHAR(20),
        puntReturnsYards VARCHAR(20),
        puntReturnsFairCatches VARCHAR(20),
        puntReturnsLgtd VARCHAR(20),
        puntingBlocked VARCHAR(20),
        puntingInside20 VARCHAR(20),
        puntingLongest VARCHAR(20),
        puntingNetYards VARCHAR(20),
        puntingTotal VARCHAR(20),
        puntingTouchbacks VARCHAR(20),
        puntingYards VARCHAR(20),
        puntingYardsPerPuntAvg VARCHAR(20),
        puntsNetYardsPerPuntAvg VARCHAR(20),
        puntingReturnYards VARCHAR(20),
        receivingFirstDowns VARCHAR(20),
        receivingLongest VARCHAR(20),
        receivingReceptions VARCHAR(20),
        receivingTouchdowns VARCHAR(20),
        receivingYards VARCHAR(20),
        receivingYardsPerReception VARCHAR(20),
        receivingTargets VARCHAR(20),
        receivingLongTouchdowns VARCHAR(20),
        rushingAttempts VARCHAR(20),
        rushingLongest VARCHAR(20),
        rushingTouchdowns VARCHAR(20),
        rushingYards VARCHAR(20),
        rushingYardsPerAttempt VARCHAR(20),
        rushingFirstDowns VARCHAR(20),
        rushingLongTouchdown VARCHAR(20)
);
        