DROP TABLE IF EXISTS Basketball.CORE__TOURNAMENTS;
CREATE TABLE Basketball.CORE__TOURNAMENTS (
    id INT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    category_id INT NOT NULL,
    FOREIGN KEY (category_id) REFERENCES CORE__CATEGORIES(id)
);