DROP TABLE IF EXISTS Football.AZURE_RAPID_L1_news;
CREATE TABLE Football.AZURE_RAPID_L1_news
(
    name VARCHAR(255) PRIMARY KEY,
    description TEXT NOT NULL,
    provider VARCHAR(255) NOT NULL,
    search_phrase VARCHAR(255) NOT NULL,
    date_published TIMESTAMP NOT NULL,
    when_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS Basketball.AZURE_RAPID_L1_news;
CREATE TABLE Basketball.AZURE_RAPID_L1_news
(
    name VARCHAR(255) PRIMARY KEY,
    description TEXT NOT NULL,
    provider VARCHAR(255) NOT NULL,
    search_phrase VARCHAR(255) NOT NULL,
    date_published TIMESTAMP NOT NULL,
    when_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS Tennis.AZURE_RAPID_L1_news;
CREATE TABLE Tennis.AZURE_RAPID_L1_news
(
    name VARCHAR(255) PRIMARY KEY,
    description TEXT NOT NULL,
    provider VARCHAR(255) NOT NULL,
    search_phrase VARCHAR(255) NOT NULL,
    date_published TIMESTAMP NOT NULL,
    when_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS Cricket.AZURE_RAPID_L1_news;
CREATE TABLE Cricket.AZURE_RAPID_L1_news
(
    name VARCHAR(255) PRIMARY KEY,
    description TEXT NOT NULL,
    provider VARCHAR(255) NOT NULL,
    search_phrase VARCHAR(255) NOT NULL,
    date_published TIMESTAMP NOT NULL,
    when_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS Motorsport.AZURE_RAPID_L1_news;
CREATE TABLE Motorsport.AZURE_RAPID_L1_news
(
    name VARCHAR(255) PRIMARY KEY,
    description TEXT NOT NULL,
    provider VARCHAR(255) NOT NULL,
    search_phrase VARCHAR(255) NOT NULL,
    date_published TIMESTAMP NOT NULL,
    when_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS Baseball.AZURE_RAPID_L1_news;
CREATE TABLE Baseball.AZURE_RAPID_L1_news
(
    name VARCHAR(255) PRIMARY KEY,
    description TEXT NOT NULL,
    provider VARCHAR(255) NOT NULL,
    search_phrase VARCHAR(255) NOT NULL,
    date_published TIMESTAMP NOT NULL,
    when_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);