USE db_name;
DROP TABLE IF EXISTS BANK__LOGOS;
CREATE TABLE BANK__LOGOS (
	file_name VARCHAR(255) PRIMARY KEY,
	full_path VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS BANK__BACKGROUNDS;
CREATE TABLE BANK__BACKGROUNDS (
    file_name VARCHAR(255) PRIMARY KEY,
    full_path VARCHAR(255) NOT NULL
);